### PR TITLE
Support Iterator, Iterable and Function API types

### LINKED ISSUE #34: Support Iterator, Iterable and Function API types
Follows-up on https://github.com/vert-x3/vertx-codegen/pull/255 (3.7.1)

This, among other usability enhancements, will simply usage of Postgres Client `PgRowSet`.

### PR DESCRIPTION
**Pull request by tsegismont**
Fixes #34

### CODE REVIEW

**Comment by tsegismont** [comment]
@cescoffier can you please review?

**Comment by cescoffier** [comment]
pretty cool!

**Comment by tsegismont** [comment]
@cescoffier thanks! Please ping when you will upgrade Quarkus. I'll update the the quickstart and guide for Pg Client.

**Comment by FroMage** [comment]
OH WOW EXCELLENT!!!

**Pull request merged**
